export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const STATE = "STATE";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const ADD_CATEGORIES = "ADD_CATEGORIES"; 